import stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  upload: {
    display: "flex",
    flexWrap: "wrap",
  },
  upload$host: {
    display: "none",
  },
  upload$trigger: {
    display: "inline-flex",
  },
  upload$files: {
    flexBasis: "100%",
    flexShrink: 0,
    display: "block",
    marginTop: "8px",
    marginBottom: "8px",
  },
  upload$files$title: {
    fontSize: "12px",
    lineHeight: "16px",
    color: "rgba(28,31,35,.62)",
    marginBottom: "4px",
  },
  upload$files$title$clear: {
    marginLeft: "8px",
    cursor: "pointer",
    color: "rgba(0,100,250, 1)",
  },
  upload$files$main: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginBottom: "8px",
  },
  upload$files$item: {
    borderRadius: "6px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "52px",
    width: "260px",
    backgroundColor: "rgba(46,50,56,.05)",
    cursor: "pointer",
  },
  upload$files$item$preview: {
    height: "36px",
    width: "36px",
    color: "rgba(28,31,35,.62)",
    margin: "8px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "3px",
    flexShrink: 0,
  },
  upload$files$item$preview$placeholder: {
    backgroundColor: "rgba(167,171,176, 1)",
    color: "rgba(255,255,255, 1)",
    fontSize: "20px",
  },
  upload$files$item$info: {
    display: "flex",
    flexWrap: "wrap",
    flex: "1 1",
  },
  upload$files$item$close: {
    padding: "4px",
    color: "rgba(28,31,35,.8)",
    marginLeft: "8px",
    marginRight: "8px",
    flexShrink: 0,
    height: "24px",
  },
  upload$files$item$info$text: {
    display: "flex",
    alignItems: "center",
    flexBasis: "100%",
  },
  upload$files$item$info$name: {
    width: 0,
    flex: "1 1",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "inline-block",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 600,
    color: "rgba(28,31,35,1)",
  },
  upload$files$item$info$size: {
    fontSize: "12px",
    lineHeight: "16px",
    fontWeight: 400,
    marginLeft: "8px",
    color: "rgba(28,31,35,.62)",
    marginTop: "1px",
  },
  upload$files$item$info$control: {
    display: "flex",
  },
  upload$files$item$info$message: {
    color: "rgba(249,57,32,1)",
    fontSize: "12px",
    lineHeight: "16px",
    display: "flex",
    alignItems: "center",
  },
  upload$files$item$info$retry: {
    color: "rgba(0,100,250, 1)",
    cursor: "pointer",
    marginLeft: "8px",
    fontSize: "12px",
    lineHeight: "16px",
  },
});
