import stylex from "@stylexjs/stylex";
import { shapes } from "../../themes/tokens/shape.stylex";
import { spacings } from "../../themes/tokens/spacing.stylex";

export const styles = stylex.create({
  upload: {
    display: "flex",
    flexWrap: "wrap",
  },
  upload$host: {
    display: "none",
  },
  upload$trigger: {
    display: "inline-flex",
  },
  upload$trigger$picture: {
    backgroundColor: "rgba(46,50,56,.05)",
    width: "92px",
    height: "92px",
    fontSize: "14px",
    boxSizing: "border-box",
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    border: "2px dashed rgba(28,31,35,.08)",
    color: "rgba(107,112,117,1)",
    borderRadius: shapes.corner$xs,
    cursor: "pointer",
  },
  upload$files: {
    flexBasis: "100%",
    flexShrink: 0,
    display: "block",
    marginTop: spacings.margin$1,
    marginBottom: spacings.margin$1,
  },
  upload$files$title: {
    fontSize: "12px",
    lineHeight: "16px",
    color: "rgba(28,31,35,.62)",
    marginBottom: spacings["margin$0.5"],
  },
  upload$files$title$clear: {
    marginLeft: spacings.margin$1,
    cursor: "pointer",
    color: "rgba(0,100,250, 1)",
  },
  upload$files$main: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginBottom: spacings.margin$1,
  },
  upload$files$item: {
    borderRadius: shapes.corner$sm,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "52px",
    width: "260px",
    backgroundColor: "rgba(46,50,56,.05)",
    cursor: "pointer",
  },
  upload$files$item$preview: {
    height: "36px",
    width: "36px",
    color: "rgba(28,31,35,.62)",
    margin: spacings.margin$1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: shapes.corner$xs,
    flexShrink: 0,
  },
  upload$files$item$preview$placeholder: {
    backgroundColor: "rgba(167,171,176, 1)",
    color: "rgba(255,255,255, 1)",
    fontSize: "20px",
  },
  upload$files$item$info: {
    display: "flex",
    flexWrap: "wrap",
    flex: "1 1",
  },
  upload$files$item$close: {
    padding: spacings.padding$1,
    color: "rgba(28,31,35,.8)",
    marginLeft: spacings.margin$1,
    marginRight: spacings.margin$1,
    flexShrink: 0,
    height: "24px",
  },
  upload$files$item$info$text: {
    display: "flex",
    alignItems: "center",
    flexBasis: "100%",
  },
  upload$files$item$info$name: {
    width: 0,
    flex: "1 1",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "inline-block",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 600,
    color: "rgba(28,31,35,1)",
  },
  upload$files$item$info$size: {
    fontSize: "12px",
    lineHeight: "16px",
    fontWeight: 400,
    marginLeft: spacings.margin$1,
    color: "rgba(28,31,35,.62)",
    marginTop: "1px",
  },
  upload$files$item$info$control: {
    display: "flex",
  },
  upload$files$item$info$message: {
    color: "rgba(249,57,32,1)",
    fontSize: "12px",
    lineHeight: "16px",
    display: "flex",
    alignItems: "center",
  },
  upload$files$item$info$retry: {
    color: "rgba(0,100,250, 1)",
    cursor: "pointer",
    marginLeft: spacings.margin$1,
    fontSize: "12px",
    lineHeight: "16px",
  },
  upload$files$picture$card: {
    width: "92px",
    height: "92px",
    borderRadius: shapes.corner$xs,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    position: "relative",
    overflow: "hidden",

    ["::before"]: {
      backgroundColor: "rgba(22,22,26,0.6)",
      content: "",
      position: "absolute",
      inset: 0,
      visibility: "hidden",
    },

    [":hover"]: {},
  },
  upload$files$picture$card$fail: {
    border: "1px solid rgba(249,57,32,1)",
    outline: "1px solid rgba(249,57,32,1)",
  },
  upload$files$picture$img: {
    width: "92px",
    height: "92px",
    objectFit: "cover",
  },
  upload$files$picture$remove: {
    display: "inline-flex",
    position: "absolute",
    top: "8px",
    right: "8px",
    cursor: "pointer",
    fontSize: "16px",
    color: "rgba(255,255,255,1)",
  },
  upload$files$picture$progress: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%,-50%)",
    width: "80%",
  },
  upload$files$picture$retry: {
    backgroundColor: "rgba(255,255,255,1)",
    width: "24px",
    height: "24px",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "rgba(0,100,250, 1)",
    borderRadius: shapes.corner$circle,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    fontSize: "16px",
  },
  upload$files$picture$message: {
    position: "absolute",
    bottom: "6px",
    right: "6px",
    color: "rgba(249,57,32,1)",
    fontSize: "16px",
  },
});
