import "normalize.css";
import { CategoryProvider } from "./_components/category-context";

export const metadata = {
  title: "Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN" style={{ height: "100%" }}>
      <body style={{ height: "100%" }}>
        <CategoryProvider>{children}</CategoryProvider>
      </body>
    </html>
  );
}
