import { CategoryProvider } from "./_components/category-context";
import Document from "./_layouts/document";
import "normalize.css";
import "./_styles/global.css";
import { Suspense } from "react";

export const metadata = {
  title: "Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN">
      <body>
        <CategoryProvider>
          <Suspense fallback={<LoadingSpinner />}>
            <Document>{children}</Document>
          </Suspense>
        </CategoryProvider>
      </body>
    </html>
  );
}

function LoadingSpinner() {
  return <div>Loading...</div>;
}
