import type { Metadata } from "next";
import Document from "@/layout/document";
import "normalize.css";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Document>{children}</Document>
      </body>
    </html>
  );
}
