import stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    width: 240,
    display: "inline-flex",
    borderRight: "1px solid rgba(28,31,35,.08)",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  inner: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  subRoot: {},
  subTitle: {
    display: "flex",
    width: "100%",
    justifyContent: "flex-start",
    height: "36px",
    alignItems: "center",
    padding: "8px 12px",
    boxSizing: "border-box",
    marginBottom: "8px",
    cursor: "pointer",
  },
  collapsibleWrap: {},
  icon: {
    minWidth: "20px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "14px",
  },
  toggleIcon: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  item: {
    height: "36px",
    cursor: "pointer",
    display: "flex",
    padding: "8px 12px",
    fontSize: "14px",
    lineHeight: "20px",
    alignItems: "center",
    boxSizing: "border-box",
    marginBottom: "8px",
  },
});
